baseURL = "https://loving-babbage-26f89d.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "The Red Tent Stockholm"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "sample-page"
name = "Frequently Asked"
weight = 4
[[menu.main]]
URL = "contact"
name = "Join In"
weight = 3
[[menu.main]]
URL = "about"
name = "About Us"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "Red Tent // Stockholm"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "A gathering for all women who want to reflect on their womanhood and share space with others! <br><br> We meet at every new moon to enjoy each other's company, to warm each other's hearts and to refresh our souls."
[params.call_to_action]
button_label = "Join In"
button_url = "contact"
content = "All women are welcome to our gatherings! Add your email to our list for information about our next meeting."
enable = true
title = "Would you like to join us?"
[params.footer]
content = "Red Tent Stockholm is a community organization for all who wish to meet other women and to enjoy community and support."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
