baseURL = "https://loving-babbage-26f89d.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Stockholm Women's Circle"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "contact"
name = "Join In"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "A website for a women's circle in stockholm"
[params.banner]
heading = "Red Tent // Stockholm"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Red Tent Stockholm will meet for the first time on the next new moon: July 20th. <br> <br> This will be a gathering for all women who want to reflect on their womanhood and share space with others! <br><br> We will warm each other's hearts and refresh our souls."
[params.call_to_action]
button_label = "Join In"
button_url = "contact"
content = "All women are welcome to take part! Add your email to our list for information about our first meeting on July 20th."
enable = true
title = "Would you like to join us?"
[params.footer]
content = "Red Tent Stockholm is a newly organized community organization for all who wish to meet other women and to enjoy community and support."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
